
# Site settings
title: Rishiraj Girmal
email: rgirmal@umass.edu
email2: rishirajmay2000@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Your info
twitter_username: yourusername
github_username: rishiraj-rpg
linkedin_username: rishirajgirmal

# Navigation (optional - for header menu)
header_pages:
  - about.markdown
  - blogs.markdown
  - resume.markdown
  - other_projects.markdown

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed



# Show excerpts on homepage
show_excerpts: false